// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Model$Bgquickstartcom from "./Model.bs.js";
import * as Layout$Bgquickstartcom from "./Layout.bs.js";

import './css/styles.css'
import './css/tailwind.css'
;

function App(Props) {
  return React.createElement(Model$Bgquickstartcom.make, {
              children: React.createElement(Layout$Bgquickstartcom.Main.make, {})
            });
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
