// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

var range = Belt_Array.range(2, 10);

export {
  range ,
  
}
/* range Not a pure module */
