// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Icon$Arrow(Props) {
  var heightOpt = Props.height;
  var widthOpt = Props.width;
  var fillOpt = Props.fill;
  var height = heightOpt !== undefined ? heightOpt : "100%";
  var width = widthOpt !== undefined ? widthOpt : "100%";
  var fill = fillOpt !== undefined ? fillOpt : "currentColor";
  return React.createElement("svg", {
              height: height,
              width: width,
              viewBox: "0 0 24 24",
              xmlns: "http://www.w3.org/2000/svg"
            }, React.createElement("g", {
                  fill: fill
                }, React.createElement("g", undefined, React.createElement("path", {
                          d: "M19 11H7.14l3.63-4.36a1 1 0 1 0-1.54-1.28l-5 6a1.19 1.19 0 0 0-.09.15c0 .05 0 .08-.07.13A1 1 0 0 0 4 12a1 1 0 0 0 .07.36c0 .05 0 .08.07.13a1.19 1.19 0 0 0 .09.15l5 6A1 1 0 0 0 10 19a1 1 0 0 0 .64-.23 1 1 0 0 0 .13-1.41L7.14 13H19a1 1 0 0 0 0-2z"
                        }))));
}

var Arrow = {
  make: Icon$Arrow
};

function Icon$Shuffle(Props) {
  var heightOpt = Props.height;
  var widthOpt = Props.width;
  var fillOpt = Props.fill;
  var height = heightOpt !== undefined ? heightOpt : "100%";
  var width = widthOpt !== undefined ? widthOpt : "100%";
  var fill = fillOpt !== undefined ? fillOpt : "currentColor";
  return React.createElement("svg", {
              height: height,
              width: width,
              viewBox: "0 0 24 24",
              xmlns: "http://www.w3.org/2000/svg"
            }, React.createElement("g", {
                  fill: fill
                }, React.createElement("g", undefined, React.createElement("path", {
                          d: "M18.71 14.29a1 1 0 0 0-1.42 1.42l.29.29H16a4 4 0 0 1 0-8h1.59l-.3.29a1 1 0 0 0 0 1.42A1 1 0 0 0 18 10a1 1 0 0 0 .71-.29l2-2A1 1 0 0 0 21 7a1 1 0 0 0-.29-.71l-2-2a1 1 0 0 0-1.42 1.42l.29.29H16a6 6 0 0 0-5 2.69A6 6 0 0 0 6 6H4a1 1 0 0 0 0 2h2a4 4 0 0 1 0 8H4a1 1 0 0 0 0 2h2a6 6 0 0 0 5-2.69A6 6 0 0 0 16 18h1.59l-.3.29a1 1 0 0 0 0 1.42A1 1 0 0 0 18 20a1 1 0 0 0 .71-.29l2-2A1 1 0 0 0 21 17a1 1 0 0 0-.29-.71z"
                        }))));
}

var Shuffle = {
  make: Icon$Shuffle
};

export {
  Arrow ,
  Shuffle ,
  
}
/* react Not a pure module */
