// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactDom from "react-dom";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ServiceWorker from "./serviceWorker";
import * as App$Bgquickstartcom from "./App.bs.js";

var registerServiceWorker = ServiceWorker.register;

var rootQuery = document.querySelector("#root");

if (!(rootQuery == null)) {
  ReactDom.render(React.createElement(App$Bgquickstartcom.make, {}), rootQuery);
}

Curry._1(registerServiceWorker, undefined);

var rootQuery$1 = (rootQuery == null) ? undefined : Caml_option.some(rootQuery);

export {
  registerServiceWorker ,
  rootQuery$1 as rootQuery,
  
}
/* registerServiceWorker Not a pure module */
