// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as FramerMotion from "framer-motion";
import * as Model$Bgquickstartcom from "./Model.bs.js";
import * as PlayerCountGrid$Bgquickstartcom from "./PlayerCountGrid.bs.js";
import * as StartPlayerSpinner$Bgquickstartcom from "./StartPlayerSpinner.bs.js";

function Layout$Header(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("h1", {
                  className: "text-4xl font-bold text-gray-200"
                }, "BG QuickStart"), React.createElement("h2", {
                  className: "mb-6 text-sm text-gray-500"
                }, "Built by ", React.createElement("a", {
                      className: "text-gray-500 underline transition duration-500 ease-out hover:text-gray-300",
                      href: "https://github.com/imjoshellis",
                      rel: "noopener noreferrer",
                      target: "_blank"
                    }, "@imjoshellis")));
}

var Header = {
  make: Layout$Header
};

var initial = {
  opacity: 0.0,
  scale: 0.9,
  y: -10
};

var animate = {
  opacity: 1.0,
  scale: 1.0,
  y: 0
};

var exit = {
  opacity: 0.0,
  scale: 0.9,
  y: 10
};

var transition = {
  duration: 0.1,
  ease: "easeOut"
};

function Layout$ThePage(Props) {
  var state = React.useContext(Model$Bgquickstartcom.State.ctx);
  var count = state.count;
  var tmp;
  var exit$1 = 0;
  if (count !== undefined) {
    var player = state.player;
    if (player !== undefined) {
      tmp = React.createElement(FramerMotion.motion.div, {
            children: React.createElement(StartPlayerSpinner$Bgquickstartcom.make, {
                  count: count,
                  player: player,
                  angle: state.angle,
                  prevAngle: state.prevAngle
                }),
            exit: exit,
            initial: initial,
            animate: animate,
            transition: transition,
            key: "spinner"
          });
    } else {
      exit$1 = 1;
    }
  } else {
    exit$1 = 1;
  }
  if (exit$1 === 1) {
    tmp = React.createElement(FramerMotion.motion.div, {
          children: React.createElement(PlayerCountGrid$Bgquickstartcom.make, {}),
          exit: exit,
          initial: initial,
          animate: animate,
          transition: transition,
          key: "grid"
        });
  }
  return React.createElement(FramerMotion.AnimatePresence, {
              initial: false,
              exitBeforeEnter: true,
              children: tmp
            });
}

var ThePage = {
  initial: initial,
  animate: animate,
  exit: exit,
  transition: transition,
  make: Layout$ThePage
};

function Layout$Main(Props) {
  return React.createElement("div", {
              className: "flex flex-col items-center justify-center px-4 py-8 text-gray-300 bg-gray-900 App"
            }, React.createElement(Layout$Header, {}), React.createElement(Layout$ThePage, {}));
}

var Main = {
  make: Layout$Main
};

export {
  Header ,
  ThePage ,
  Main ,
  
}
/* react Not a pure module */
