// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as FramerMotion from "framer-motion";
import * as Model$Bgquickstartcom from "./Model.bs.js";
import * as Constants$Bgquickstartcom from "./Constants.bs.js";

function PlayerCountGrid$CountButton(Props) {
  var num = Props.num;
  var dispatch = React.useContext(Model$Bgquickstartcom.Dispatch.ctx);
  var whileHover = {
    backgroundColor: "#CCD5E1",
    scale: 1.05
  };
  var whileTap = {
    backgroundColor: "#EDF2F7",
    scale: 1.05
  };
  var onClick = function (param) {
    return Curry._1(dispatch, /* Roll */{
                count: num
              });
  };
  return React.createElement(FramerMotion.motion.div, {
              children: num,
              whileHover: whileHover,
              whileTap: whileTap,
              onClick: onClick,
              className: "px-8 py-8 text-xl font-bold text-gray-900 bg-gray-600 rounded-lg shadow-lg cursor-pointer"
            });
}

var CountButton = {
  make: PlayerCountGrid$CountButton
};

function PlayerCountGrid(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "grid grid-cols-3 gap-4"
                }, Belt_Array.map(Constants$Bgquickstartcom.range, (function (n) {
                        return React.createElement(PlayerCountGrid$CountButton, {
                                    num: n,
                                    key: String(n)
                                  });
                      }))));
}

var make = PlayerCountGrid;

export {
  CountButton ,
  make ,
  
}
/* react Not a pure module */
